### ISSUE TITLE
Package description should be more expository

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk-package-pushnotifications#12]
![screen shot 2016-06-23 at 12 07 58 pm](https://cloud.githubusercontent.com/assets/4741620/16310604/2d12cf08-393b-11e6-8f33-141cc017730f.png)

a longer description that doesn't define the package in terms of itself?

**Comment by starpit** [comment]
hi, my suggestion was to change the description field, aren't we in charge of that part?

**Comment by AnanthaKrish** [comment]
Description is changed to `This package supports sending push notifications to your mobile device, using the IBM Bluemix Push Notifications service.`
