### ISSUE TITLE
action description has odd casing, and perhaps could be more expository

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk-package-pushnotifications#13]
![screen shot 2016-06-23 at 12 09 13 pm](https://cloud.githubusercontent.com/assets/4741620/16310649/5e228a3e-393b-11e6-9230-ca88cedb3476.png)

maybe don't capitalize the P in Push? and, as with #12, we have the space to be a bit more expository, if helpful. e.g. 

```
Send a push notification to the specified device, using the IBM pushnotification service.
```

**Comment by AnanthaKrish** [comment]
Changed the action description to `Send push notification to all application users or to a specific set of devices`
