### ISSUE TITLE
The push notification package display name Change to `MOBILE PUSH`

### ISSUE THREAD

**Issue by AnanthaKrish** [openwhisk/openwhisk-package-pushnotifications#18]
<img width="286" alt="screen shot 2016-06-24 at 4 18 47 pm" src="https://cloud.githubusercontent.com/assets/16939018/16336247/a4ff4f98-3a29-11e6-916b-85cae0dce72d.png">
@starpit 
I have noticed that the push notification package display name is changed to `MOBILE PUSH`. The name should be `PUSH NOTIFICATIONS`.

**Comment by starpit** [comment]
in discussion with @sjfink we've decided to use this name temporarily in the UI, until we can find a way to display longer names. "Push Notifications" is quite long.
