### ISSUE TITLE
install.sh fails

### ISSUE THREAD

**Issue by nwspeete-ibm** [openwhisk/openwhisk-package-pushnotifications#24]
May be a regression in install.sh. Anantha is testing to see if he sees the same issue on his setup.

**Comment by nwspeete-ibm** [comment]
Error is :  --shared yes pushnotifications -a description 'This package supports sending push notifications to your mobile device, using the IBM Bluemix Push Notifications service.' -a parameters '[ {"name":"appId", "required":true, "description":"Bluemix application GUID"}, {"name":"appSecret", "required":true, "bindTime":true, "type":"password", "description":"Bluemix Push Service Secret"}]' -a prettyName 'Push Notifications'
error: [Errno 60] Operation timed out

**Comment by AnanthaKrish** [comment]
vagrant@Ananthas-M-whisk:~/bluewhisk/blue/catalog$ ./installPushnotifications.sh 
Cloning into '/home/vagrant/bluewhisk/blue/catalog/extra-packages/pushnotifications'...
remote: Counting objects: 85, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 85 (delta 3), reused 0 (delta 0), pack-reused 74
Unpacking objects: 100% (85/85), done.
Checking connectivity... done.
Note: checking out '9b25065da118bb65fa122da4c01cd078413cfe4c'.
​
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
​
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
​
  git checkout -b new_branch_name
​
HEAD is now at 9b25065... Change values to json
+ '[' 3 -eq 0 ']'
+ APIHOST=172.17.0.1
+ AUTH=19bc46b1-71f6-4ed5-8c54-816aa4f8c502:OHjzO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
+ WSK_CLI=/home/vagrant/bluewhisk/open/bin/wsk
+ echo Installing pushnotifications package.
Installing pushnotifications package.
+ /home/vagrant/bluewhisk/open/bin/wsk --apihost 172.17.0.1 package update --auth 19bc46b1-71f6-4ed5-8c54-816aa4f8c502:OHjzO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP --shared yes pushnotifications -a description 'This package supports sending push notifications to your mobile device, using the IBM Bluemix Push Notifications service.' -a parameters '[ {"name":"appId", "required":true, "description":"Bluemix application GUID"}, {"name":"appSecret", "required":true, "bindTime":true, "type":"password", "description":"Bluemix Push Service Secret"}]' -a prettyName 'Push Notifications'
ok: updated package pushnotifications
+ /home/vagrant/bluewhisk/open/bin/wsk --apihost 172.17.0.1 action update --auth 19bc46b1-71f6-4ed5-8c54-816aa4f8c502:OHjzO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP --shared yes pushnotifications/webhook webhook.js -a feed true -a description 'pushnotifications feed' -a parameters '[ {"name":"appId", "required":true, "description":"Bluemix application GUID"}, {"name":"appSecret", "required":true, "bindTime":true, "type":"password", "description":"Bluemix Push Service Secret"},{"name":"events", "required":true, "description":"Name of the event user want to subscribe"} ]' -a sampleInput '{"appId":"xxx-xxx-xx", "appSecret":"yyy-yyy-yyy", "events":"onDeviceRegister"}' -a sampleOutput '{"tagName": "tagName","eventType": "onDeviceRegister","applicationId": "xxx-xxx-xx"}'
ok: updated action webhook
+ /home/vagrant/bluewhisk/open/bin/wsk --apihost 172.17.0.1 action update --auth 19bc46b1-71f6-4ed5-8c54-816aa4f8c502:OHjzO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP --shared yes pushnotifications/sendMessage sendMessage.js -a description 'Send push notification to all application users or to a specific set of devices' -a parameters '[ {"name":"appId", "required":true, "description":"Bluemix application GUID"}, {"name":"appSecret", "required":true, "bindTime":true, "type":"password", "description":"Bluemix Push Service Secret"}, {"name":"text", "required":true, "description":"The notification message to be shown to the user"}, {"name":"url", "required":false, "description":"An optional URL that can be sent along with the alert"}, {"name":"deviceIds", "required":false, "description":"Array of device IDs"}, {"name":"platforms", "required":false, "description":"Array of device platform"},{"name":"tagNames", "required":false, "description":"Array of tag names"},{"name":"gcmPayload", "required":false, "description":"Additional payload"},{"name":"gcmSound", "required":false, "description":"Sound file name"},{"name":"gcmCollapseKey", "required":false, "description":"This parameter identifies a group of messages"},{"name":"gcmDelayWhileIdle", "required":false, "description":"Send message when device is active"}, {"name":"gcmPriority", "required":false, "description":"Sets the priority of the message"}, {"name":"gcmTimeToLive", "required":false, "description":"Time limit for message to be delievered"}, {"name":"apnsBadge", "required":false, "description":"Value for Badge"}, {"name":"apnsCategory", "required":false, "description":"The category name"}, {"name":"apnsIosActionKey", "required":false, "description":"Title for the push notification action Key"},{"name":"apnsPayload", "required":false, "description":"Additional payload"},{"name":"apnsType", "required":false, "description":"Push notification type name"},{"name":"apnsSound", "required":false, "description":"APNS sound name"}]' -a sampleInput '{"appId":"xxx-xxx-xx", "appSecret":"yyy-yyy-yyy", "text":"hi there"}' -a sampleOutput '{"pushResponse": {"messageId":"11111s","message":{"message":{"alert":"register for tag"}}}}'
ok: updated action sendMessage
pushnotifications package ERRORS =
vagrant@Ananthas-M-whisk:~/bluewhisk/blue/catalog$

**Comment by AnanthaKrish** [comment]
I am not getting that operation timeout issue. It executed for me

`ok: updated action sendMessage
pushnotifications package ERRORS =`
