### ISSUE TITLE
install.sh should take parameters via arguments not ENV variables

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk-package-pushnotifications#5]
install.sh should be explicit and required the parameters to always be pass.
This way we avoid using and ENV that might be set for other deployments

**Comment by nwspeete-ibm** [comment]
This can be accomplished with positional arguments to the install.sh: "First arg: $1". Carlos has approved this positional method.

**Comment by csantanapr** [comment]
@nwspeete-ibm I think I would like to see something like this

The script to have a signature of `install.sh <apihost> <authkey> <pathtowskcli>`

user needs to pass 3 arguments for the script to work.

`install.sh 172.0.1.1 b23cdfnfffogog..  /home/vagrant/bin/wsk`

or running with no parameters prints usage

```
install.sh
Usage:
   install.sh <apihost> <authkey> <pathtowskcli>
```
