### ISSUE TITLE
Push request being rejected due to invalid (valid) JSON

### ISSUE THREAD

**Issue by meyumeapps** [openwhisk/openwhisk-package-pushnotifications#74]
This seems to have been rejected for some reason?

I think it's possibly the Spanish characters ? It validates fine with JSON Lint:
https://jsonlint.com

`{
	"duration": 168,
	"name": "PushSender",
	"subject": "scott.wilsonbilling@mac.com",
	"activationId": "1e570a7ef0064b45a1737f60ea2dfb71",
	"publish": false,
	"annotations": [{
		"key": "limits",
		"value": {
			"timeout": 120000,
			"memory": 128,
			"logs": 10
		}
	}, {
		"key": "path",
		"value": "Nibiru_prod-us-south/WG/PushSender"
	}, {
		"key": "causedBy",
		"value": "sequence"
	}],
	"version": "0.0.27",
	"response": {
		"result": {
			"apnstitle": "Tampico Today",
			"apnsType": "DEFAULT",
			"apnsSound": "Notification_sound.m4a",
			"deviceIds": ["40294237-3F2B-4E92-B34C-BB2562DDD1FF"],
			"text": "Tormentas matinales. Máxima de 33 C. Vientos del ESE de 15 a 30 km/h. 40% probab. de lluvia. Tonight: Cielo mayormente despejado. Es posible que se produzca una tormenta o chubasco dispersos. Mínima de 26 C. Vientos del E de 15 a 30 km/h.",
			"apnsPayload": {
				"weathergods": {
					"placeName": "Tampico",
					"timeZoneId": "America/Monterrey",
					"scheduleType": 2,
					"units": 2,
					"type": 611,
					"dayIndex": 0,
					"daySummary": "Tormentas matinales. Máxima de 33 C. Vientos del ESE de 15 a 30 km/h. 40% probab. de lluvia.",
					"nightSummary": "Cielo mayormente despejado. Es posible que se produzca una tormenta o chubasco dispersos. Mínima de 26 C. Vientos del E de 15 a 30 km/h."
				}
			},
			"appId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
			"apnsAttachmentUrl": "http://dummy.com",
			"appSecret": "XXXXXXXXXXXXXXXXXXXXXXXXX"
		},
		"success": true,
		"status": "success"
	},
	"cause": "98c444f4eef142d9b791b80673567622",
	"end": 1493812801259,
	"logs": ["2017-05-03T12:00:01.258328485Z stdout: Received args: [\"input\": [\"text\": \"Tormentas matinales. Máxima de 33 C. Vientos del ESE de 15 a 30 km/h. 40% probab. de lluvia. Tonight: Cielo mayormente despejado. Es posible que se produzca una tormenta o chubasco dispersos. Mínima de 26 C. Vientos del E de 15 a 30 km/h.\", \"title\": \"Tampico Today\", \"deviceId\": \"40294237-3F2B-4E92-B34C-BB2562DDD1FF\", \"payload\": [\"weathergods\": [\"dayIndex\": 0, \"timeZoneId\": \"America/Monterrey\", \"placeName\": \"Tampico\", \"nightSummary\": \"Cielo mayormente despejado. Es posible que se produzca una tormenta o chubasco dispersos. Mínima de 26 C. Vientos del E de 15 a 30 km/h.\", \"type\": 611, \"units\": 2, \"daySummary\": \"Tormentas matinales. Máxima de 33 C. Vientos del ESE de 15 a 30 km/h. 40% probab. de lluvia.\", \"scheduleType\": 2]]]]"],
	"start": 1493812801091,
	"namespace": "Nibiru_prod-us-south"
}`

**Comment by meyumeapps** [comment]
Here's the error for the JSON:

`FPWSE0004E: Bad Request - Invalid JSON.`

`{
	"duration": 782,
	"name": "BluemixPush",
	"subject": "scott.wilsonbilling@mac.com",
	"activationId": "6d97cce7af614440af8cf42e8b78f6c3",
	"publish": false,
	"annotations": [{
		"key": "limits",
		"value": {
			"timeout": 60000,
			"memory": 128,
			"logs": 10
		}
	}, {
		"key": "path",
		"value": "Nibiru_prod-us-south/BluemixPush"
	}, {
		"key": "causedBy",
		"value": "sequence"
	}],
	"version": "0.0.2",
	"response": {
		"result": {
			"code": "FPWSE0004E",
			"message": "Bad Request - Invalid JSON."
		},
		"success": true,
		"status": "success"
	},
	"cause": "98c444f4eef142d9b791b80673567622",
	"end": 1493812802417,
	"logs": [],
	"start": 1493812801635,
	"namespace": "Nibiru_prod-us-south"
}`

**Comment by AnanthaKrish** [comment]
Solved this issue

**Comment by csantanapr** [comment]
issue is fixed thanks @AnanthaKrish
