### ISSUE TITLE
sampleOutput should be JSON, not Result=

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk-package-pushnotifications#9]
the sampleOutput metadata in install.sh should match the structure of sampleInput, i.e. be a JSON object

**Comment by starpit** [comment]
![screen shot 2016-06-23 at 12 05 19 pm](https://cloud.githubusercontent.com/assets/4741620/16310505/c2e360e8-393a-11e6-87db-51c3916e3080.png)

observe the poorly formatted sampleOutput

**Comment by AnanthaKrish** [comment]
Solved the Sample output JSON issue.
